# Generated by Django 5.1.7 on 2025-03-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('learn-more', 'Learn more'), ('try-it-out', 'Try it out')], max_length=50)),
                ('interest', models.CharField(choices=[('machine-learning', 'Machine Learning'), ('data-analysis', 'Data Analysis'), ('healthcare', 'Healthcare')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
